<?php
$fields = array(
	'component_callout_banner' => array(
		'key' => 'component_callout_banner',
		'name' => 'callout_banner',
		'label' => 'Callout Banner',
		'display' => 'block',
		'sub_fields' => array(
			//Component Settings Tab
			array(
				'key' => 'component_callout_banner_tab_setting',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_callout_banner_component_enabled',
				'label' => 'Show This Component?',
				'name' => 'enable_component',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Enabled',
				'ui_off_text' => 'Hidden',
			),
			array(
				'key' => 'component_callout_banner_field_id',
				'label' => 'ID',
				'name' => 'id',
				'type' => 'text',
				'instructions' => 'identifier',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_callout_banner_field_class',
				'label' => 'Classes',
				'name' => 'class',
				'type' => 'text',
				'instructions' => 'additional classes',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			// Component Content Tab
			array(
				'key' => 'component_callout_banner_tab_content',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_callout_banner_component_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_callout_banner_layout_type',
				'label' => 'Layout Type',
				'name' => 'fh_layout_type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left',
					'right' => 'Right',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'text',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array(
				'key' => 'component_callout_banner_title',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '&nbsp;',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_callout_banner_feature_image',
				'label' => 'Feature Image',
				'name' => 'feature_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'svg, png, jpg, jpeg',
			),
			array(
				'key' => 'component_callout_banner_feature_description',
				'label' => 'Feature Description',
				'name' => 'feature_description',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => '',
				'toolbar' => 'basic',
				'media_upload' => 1,
				'delay' => 1,
			),
			array(
				'key' => 'component_callout_banner_cta_enabled',
				'label' => 'Enable CTA',
				'name' => 'enable_cta',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'component_callout_banner_cta_url',
				'label' => 'CTA URL',
				'name' => 'cta_url',
				'type' => 'link',
				'instructions' => 'please enter a valid url',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_callout_banner_cta_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'component_callout_banner_cta_text',
				'label' => 'CTA Text',
				'name' => 'cta_text',
				'type' => 'text',
				'instructions' => '&nbsp;',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_callout_banner_cta_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
			),
		),
	),
);
