<?php
$fields = array(
	'component_gallery_tabs' => array(
		'key' => 'component_gallery_tabs',
		'name' => 'gallery_tabs',
		'label' => 'Image Gallery Tabs',
		'display' => 'block',
		'sub_fields' => array(
			//Component Settings Tab
			array(
				'key' => 'component_gallery_tabs_tab_setting',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_gallery_tabs_component_enabled',
				'label' => 'Show This Component?',
				'name' => 'enable_component',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Enabled',
				'ui_off_text' => 'Hidden',
			),
			array(
				'key' => 'component_gallery_tabs_field_id',
				'label' => 'ID',
				'name' => 'id',
				'type' => 'text',
				'instructions' => 'identifier',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_gallery_tabs_field_class',
				'label' => 'Classes',
				'name' => 'class',
				'type' => 'text',
				'instructions' => 'additional classes',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			// Component Content Tab
			array(
				'key' => 'component_gallery_tabs_tab_content',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_gallery_tabs_component_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_gallery_tabs_title',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '&nbsp;',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '0',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_gallery_tabs_tabs_repeater',
				'label' => 'Tabs',
				'name' => 'tabs_repeater',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => '',
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'component_gallery_tabs_tabs_repeater_title',
						'label' => 'Tab Title',
						'name' => 'tab_title',
						'type' => 'text',
						'instructions' => '&nbsp;',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
					),
					array(
						"key" => "component_gallery_tabs_tabs_repeater_gallery",
						"label" => "Gallery",
						"name" => "gallery",
						"aria-label" => "",
						"type" => "gallery",
						"instructions" => "",
						"required" => 0,
						"conditional_logic" => 0,
						"wrapper" => array(
							"width" => "",
							"class" => "",
							"id" => ""
						),
						"return_format" => "array",
						"library" => "all",
						"min" => "",
						"max" => "",
						"min_width" => "",
						"min_height" => "",
						"min_size" => "",
						"max_width" => "",
						"max_height" => "",
						"max_size" => "",
						"mime_types" => "",
						"insert" => "append",
						"preview_size" => "medium"
					),
				),
			),
			array(
				'key' => 'component_gallery_tabs_cta_enabled',
				'label' => 'Enable CTA',
				'name' => 'enable_cta',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'component_gallery_tabs_cta_url',
				'label' => 'CTA URL',
				'name' => 'gallery_cta_url',
				'type' => 'link',
				'instructions' => 'please enter a valid url',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_gallery_tabs_cta_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
	)
);
