<?php
$page = get_page_by_path('history');
acf_add_local_field_group(array(
	'key' => 'brand_history_component',
	'title' => 'Brand History',
	'fields' => array(
		array(
			'key' => 'brand_history_repeater',
			'label' => 'Brand History',
			'name' => 'brand_history',
			'type' => 'repeater',
			'instructions' => 'Add a new block for every historical milestone',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'brand_history_field_id',
					'label' => 'ID',
					'name' => 'id',
					'type' => 'text',
					'instructions' => 'identifier',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'brand_history_field_class',
					'label' => 'Classes',
					'name' => 'class',
					'type' => 'text',
					'instructions' => 'additional classes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'brand_history_title',
					'label' => 'Milestone Title',
					'name' => 'milestone_title',
					'type' => 'text',
					'instructions' => '&nbsp;',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'brand_history_year',
					'label' => 'Milestone Year',
					'name' => 'milestone_year',
					'type' => 'text',
					'instructions' => '&nbsp;',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
				),
				array(
					'key' => 'brand_history_supplemental_years',
					'label' => 'Supplemental Years',
					'name' => 'supplemental_years',
					'type' => 'repeater',
					'instructions' => '&nbsp;',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => '',
					'max' => '',
					'layout' => 'block',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'brand_history_additional_year',
							'label' => 'Additional Year',
							'name' => 'additional_year',
							'type' => 'text',
							'instructions' => '&nbsp;',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
				),
				array(
					'key' => 'brand_history_milestone_description',
					'label' => 'Milestone Description',
					'name' => 'milestone_description',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 1,
				),
				array(
					'key' => 'brand_history_milestone_image',
					'label' => 'Milestone Feature Image',
					'name' => 'milestone_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => 0,
					'min_height' => 0,
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'svg, png, jpg, jpeg',
				),
				array(
					'key' => 'brand_history_layout_type',
					'label' => 'Image Location',
					'name' => 'fh_layout_type',
					'type' => 'radio',
					'instructions' => 'Only applies on tablet sized devices and up',
					'required' => 0,
					'wrapper' => array(
						'width' => '66',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'top' => 'Image Top',
						'bottom' => 'Image Bottom',
						'left' => 'Image Left',
						'right' => 'Image Right',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'text',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => $page->ID,
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));
?>