<?php
$fields = array(
    'component_horizontal_columns' => array(
        'key' => 'component_horizontal_columns',
        'name' => 'horizontal_columns',
        'label' => 'Horizontal Columns',
        'display' => 'block',
        'sub_fields' => array(
            //Component Settings Tab
            array(
                'key' => 'component_horizontal_columns_tab_setting',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'component_horizontal_columns_component_enabled',
                'label' => 'Show This Component?',
                'name' => 'enable_mobile',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => 'Enabled',
                'ui_off_text' => 'Hidden',
            ),
            array(
                'key' => 'component_horizontal_columns_field_id',
                'label' => 'ID',
                'name' => 'id',
                'type' => 'text',
                'instructions' => 'identifier',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_horizontal_columns_field_class',
                'label' => 'Classes',
                'name' => 'class',
                'type' => 'text',
                'instructions' => 'additional classes',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
            ),
            // Component Content Tab
            array(
                'key' => 'component_horizontal_columns_tab_content',
                'label' => 'Content',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_horizontal_columns_component_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'component_horizontal_columns_heading',
                'label' => 'Heading',
                'name' => 'horizontal_columns_heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_horizontal_columns_layout',
                'label' => 'Layout Type',
                'name' => 'layout_type',
                'type' => 'radio',
                'instructions' => 'This will determine the number of columns on large tablets and desktops',
                'required' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'two' => 'Two Columns',
                    'three' => 'Three Columns',
                    'four' => 'Four Columns',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'component_horizontal_columns_image_ratio',
                'label' => 'Image Aspect Ratio',
                'name' => 'image_ratio',
                'type' => 'select',
                'instructions' => 'This will determine the aspect ratio of the images in the grid. Choose from 16:9, 4:3 or 9:16',
                'required' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'none' => 'No Set Aspect Ratio',
                    '1:1' => '1:1 (Square)',
                    '16:9' => '16:9 (Landscape - Wider)',
                    '4:3' => '4:3 (Landscape - Taller)',
                    '3:4' => '3:4 (Portrait - Shorter)',
                    '9:16' => '9:16 (Portrait - Taller)',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'default_value' => 'text',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'component_horizontal_columns__image_border',
                'label' => 'Image Borders',
                'name' => 'image_border',
                'type' => 'true_false',
                'instructions' => 'Display a light grey border around images',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Enabled',
                'ui_off_text' => 'Hidden',
            ),
            array(
                'key' => 'component_horizontal_columns_repeater',
                'label' => 'Content',
                'name' => 'horizontal_columns_repeater',
                'type' => 'repeater',
                'instructions' => 'Match the number of items to the Column Layout for the best effect',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 2,
                'max' => '',
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'component_horizontal_columns_title',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'instructions' => '&nbsp;',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'component_horizontal_columns_subtitle',
                        'label' => 'Subtitle',
                        'name' => 'subtitle',
                        'type' => 'text',
                        'instructions' => 'Subtitle is displayed above the title',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array(
                        'key' => 'component_horizontal_columns_feature_image',
                        'label' => 'Feature Image',
                        'name' => 'feature_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 0,
                        'min_height' => 0,
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => 'svg, png, jpg, jpeg',
                    ),
                    array(
                        'key' => 'component_horizontal_columns_feature_description',
                        'label' => 'Feature Description',
                        'name' => 'feature_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '100',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => '',
                        'toolbar' => 'basic',
                        'media_upload' => 1,
                        'delay' => 1,
                    ),
                    array(
                        'key' => 'component_horizontal_columns_feature_link',
                        'label' => 'Feature Link',
                        'name' => 'feature_link',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'component_horizontal_columns_clickable_images',
                        'label' => 'Link Images?',
                        'name' => 'clickable_images',
                        'type' => 'true_false',
                        'instructions' => 'Make images link to the same URL as Feature Link',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enabled',
                        'ui_off_text' => 'Hidden',
                    ),
                ),
            ),
        ),
    )
);
