<?php 
// Components for product details template
acf_add_local_field_group(array(
    'key' => 'klyp_product_details_components',
    'title' => 'Product Details Component',
    'fields' => array(
        array(
            'key' => 'product_details_hero',
            'label' => 'Hero Image',
            'name' => 'product_details_hero',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_hero']['sub_fields'],
        ),
        array(
            'key' => 'product_details_horizontal_columns',
            'label' => 'Horizontal Colums',
            'name' => 'product_details_horizontal_column',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_horizontal_columns']['sub_fields'],
        ),
        array(
            'key' => 'product_details_how_it_workss',
            'label' => 'How It Works',
            'name' => 'product_details_how_it_works',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_how_it_works']['sub_fields'],
        ),
        array(
            'key' => 'product_details_features_benefits',
            'label' => 'Features and Benefits',
            'name' => 'product_details_features_benefits',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_feature_benefits']['sub_fields'],
        ),
        array(
            'key' => 'product_details_size_specifications',
            'label' => 'Size and Specifications',
            'name' => 'product_details_size_specifications',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_size_specifications']['sub_fields'],
        ),
        array(
            'key' => 'product_details_downloads',
            'label' => 'Downloads & Compliance',
            'name' => 'product_details_downloads',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_downloads']['sub_fields'],
        ),
        array(
            'key' => 'product_details_client_reviews',
            'label' => 'Client Reviews',
            'name' => 'product_details_client_reviews',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_review_slider']['sub_fields'],
        ),
        array(
            'key' => 'product_details_gallery_image',
            'label' => 'Gallery Images',
            'name' => 'product_details_gallery_image',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $product_details_component_fields['pd_component_gallery_image']['sub_fields'],
        ),
        array(
            'key' => 'product_mini_projects_lists',
            'label' => 'Similar Projects List',
            'name' => 'product_mini_projects_lists',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $projects_components_fields['component_mini_projects_lists']['sub_fields'],
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'product',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

//Product Options Field
acf_add_local_field_group(array(
    'key' => 'group_product_options',
    'title' => 'Product Options',
    'fields' => array(
        array(
            'key' => 'uom',
            'label' => 'Unit of Measurement',
            'name' => 'uom',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'default_value' => 'm<sup>2</sup>',
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
        ),
        array(
            'key' => 'product_option_repeater',
            'label' => 'Product Option',
            'name' => 'product_option_repeater',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => '',
            'sub_fields' => array(
                array(
                    'key' => 'product_option_prefix',
                    'label' => 'Prefix',
                    'name' => 'product_option_prefix',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'product_option_type',
                    'label' => 'Option',
                    'name' => 'product_option_type',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'product_option_description',
                    'label' => 'Description',
                    'name' => 'product_option_description',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => '',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'delay' => 1,
                ),
                array(
                    'key' => 'product_option_value_repeater',
                    'label' => 'Value',
                    'name' => 'product_option_value_repeater',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'product_option_value',
                            'label' => 'Value',
                            'name' => 'product_option_value',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'product_option_image',
                            'label' => 'Option Image',
                            'name' => 'product_option_image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'medium',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'product_option_price',
                            'label' => 'Price change',
                            'name' => 'product_option_price',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'product',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

//Individual Call To Action
acf_add_local_field_group(array(
    'key' => 'product_nav_custom_group',
    'title' => 'Product Call To Action (Custom)',
    'fields' => array(
        array(
            'key' => 'product_nav_custom_enabled',
            'label' => 'Custom Call To Action?',
            'name' => 'product_nav_custom_enabled',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => 'Yes',
            'ui_off_text' => 'No',
        ),
        array(
            'key' => 'product_nav_custom_cta__1',
            'label' => 'Button 1',
            'name' => 'product_nav_custom_cta__1',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'product_nav_custom_enabled',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '100',
                'class' => '100',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'product_nav_custom_cta__2',
            'label' => 'Button 2',
            'name' => 'product_nav_custom_cta__2',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'product_nav_custom_enabled',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'product',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

//Product Option Dependency Field
acf_add_local_field_group(
    array(
        'key' => 'group_product_option_dependency',
        'title' => 'Product Options Dependencies',
        'fields' => array(
            array(
                'key' => 'product_option_dependency',
                'label' => 'Product Options Dependency',
                'name' => 'product_option_dependency',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 200,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'product_option_dependency_value',
                        'label' => 'Dependency Values',
                        'name' => 'product_option_dependency_value',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'product_option_dependency_image',
                        'label' => 'Dependency Image',
                        'name' => 'product_option_dependency_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    )
);

//Product Email Attachment Field
acf_add_local_field_group(array(
    'key' => 'group_product_email_attachments',
    'title' => 'Product Email Attachments',
    'fields' => array(
        array(
            'key' => 'product_attachment_1',
            'label' => 'Product Attachment',
            'name' => 'product_attachment_1',
            'type' => 'file',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
			'key' => 'product_attachment_2',
			'label' => 'Product Attachment',
			'name' => 'product_attachment_2',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'product',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
?>
