<?php
$fields = array(
    'component_projects_showcase' => array(
        'key' => 'component_projects_showcase',
        'name' => 'projects_showcase',
        'label' => 'Projects Showcase',
        'display' => 'block',
        'sub_fields' => array(
            //Component Settings Tab
            array(
                'key' => 'component_projects_showcase_tab_setting',
                'label' => 'Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'component_projects_showcase_component_enabled',
                'label' => 'Show This Component?',
                'name' => 'enable_mobile',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => 'Enabled',
                'ui_off_text' => 'Hidden',
            ),
            array(
                'key' => 'component_projects_showcase_field_id',
                'label' => 'ID',
                'name' => 'id',
                'type' => 'text',
                'instructions' => 'identifier',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_projects_showcase_field_class',
                'label' => 'Classes',
                'name' => 'class',
                'type' => 'text',
                'instructions' => 'additional classes',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
            ),

            // Component Content Tab
            array(
                'key' => 'component_projects_showcase_tab_content',
                'label' => 'Content',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_projects_showcase_component_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'component_projects_showcase_title',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'instructions' => '&nbsp;',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_projects_showcase_feature_description',
                'label' => 'Feature Description',
                'name' => 'feature_description',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => '',
                'toolbar' => 'basic',
                'media_upload' => 1,
                'delay' => 1,
            ),
            array(
                'key' => 'component_project_showcase_firstbtn_enabled',
                'label' => 'Enable First Button',
                'name' => 'enable_first_button',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'component_project_showcase_firstbtn_text',
                'label' => 'First Button Text',
                'name' => 'firstbtn_text',
                'type' => 'text',
                'instructions' => '&nbsp;',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_project_showcase_firstbtn_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_project_showcase_firstbtn_url',
                'label' => 'First Button URL',
                'name' => 'firstbtn_url',
                'type' => 'link',
                'instructions' => 'please enter a valid url',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_project_showcase_firstbtn_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'component_project_showcase_secondbtn_enabled',
                'label' => 'Enable Second Button',
                'name' => 'enable_second_button',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'component_project_showcase_secondbtn_text',
                'label' => 'Second Button Text',
                'name' => 'secondbtn_text',
                'type' => 'text',
                'instructions' => '&nbsp;',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_project_showcase_secondbtn_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'component_project_showcase_secondbtn_url',
                'label' => 'Second Button URL',
                'name' => 'secondbtn_url',
                'type' => 'link',
                'instructions' => 'please enter a valid url',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'component_project_showcase_secondbtn_enabled',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'component_projects_showcase_repeater',
                'label' => 'Content',
                'name' => 'projects_showcase_repeater',
                'type' => 'repeater',
                'instructions' => 'Maximum 5 column only',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 5,
                'layout' => 'block',
                'button_label' => '',
                'sub_fields' => array(        
                    array(
                        'key' => 'component_projects_showcase_feature_image',
                        'label' => 'Feature Image',
                        'name' => 'feature_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => 0,
                        'min_height' => 0,
                        'min_size' => '',
                        'max_size' => '5',
                        'mime_types' => 'svg, png, jpg, jpeg',
                    ),
                ),
            ),      
        ),
    )
);
