<?php
acf_add_local_field_group(array(
    'key' => 'klyp_projects_components',
    'title' => 'Projects Component',
    'fields' => array(
        array(
            'key' => 'project_location',
            'label' => 'Project Location',
            'name' => 'project_location',
            'type' => 'text',
            'instructions' => 'This field is used for the Featured Projects block',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
        ),
        array(
            'key' => 'project_year',
            'label' => 'Project Year',
            'name' => 'project_year',
            'type' => 'text',
            'instructions' => 'This field is used for the Featured Projects block',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
        ),
        array(
            'key' => 'page_hero',
            'label' => 'Feature Hero',
            'name' => 'page_hero',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_hero']['sub_fields'],
        ),
        array(
            'key' => 'projects_home_introduction',
            'label' => 'Feature Home Introduction',
            'name' => 'projects_home_introduction',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_home_introduction']['sub_fields'],
        ),
        array(
            'key' => 'projects_feature_call_to_action_summary',
            'label' => 'Feature Call To Action Summary',
            'name' => 'projects_feature_call_to_action_summary',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_feature_call_to_action']['sub_fields'],
        ),
        array(
            'key' => 'projects_overlaid_images_4',
            'label' => 'Feature Overlaid Images 4',
            'name' => 'projects_overlaid_images_4',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $projects_components_fields['component_overlaid_images']['sub_fields'],
        ),
        array(
            'key' => 'projects_feature_call_to_action_our_solution',
            'label' => 'Feature Call To Action Our Solution',
            'name' => 'projects_feature_call_to_action_our_solution',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_feature_call_to_action']['sub_fields'],
        ),
        array(
            'key' => 'projects_feature_call_to_action_supply_and_install',
            'label' => 'Feature Call To Action Supply And Install',
            'name' => 'projects_feature_call_to_action_supply_and_install',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $component_fields['component_feature_call_to_action']['sub_fields'],
        ),
        array(
            'key' => 'projects_overlaid_images_5',
            'label' => 'Feature Overlaid Images 5',
            'name' => 'projects_overlaid_images_5',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $projects_components_fields['component_overlaid_images']['sub_fields'],
        ),
        array(
            'key' => 'projects_mini_projects_lists',
            'label' => 'Feature Mini Projects List',
            'name' => 'projects_mini_projects_lists',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => $projects_components_fields['component_mini_projects_lists']['sub_fields'],
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'project',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
?>
