<?php
$fields = array(
	'component_text_tabs' => array(
		'key' => 'component_text_tabs',
		'name' => 'text_tabs',
		'label' => 'Text Tabs',
		'display' => 'block',
		'sub_fields' => array(
			//Component Settings Tab
			array(
				'key' => 'component_text_tabs_tab_setting',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_text_tabs_component_enabled',
				'label' => 'Show This Component?',
				'name' => 'enable_component',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => 'Enabled',
				'ui_off_text' => 'Hidden',
			),
			array(
				'key' => 'component_text_tabs_field_id',
				'label' => 'ID',
				'name' => 'id',
				'type' => 'text',
				'instructions' => 'identifier',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_text_tabs_field_class',
				'label' => 'Classes',
				'name' => 'class',
				'type' => 'text',
				'instructions' => 'additional classes',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
			),
			// Component Content Tab
			array(
				'key' => 'component_text_tabs_tab_content',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'component_text_tabs_component_enabled',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'component_text_tabs_title',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '&nbsp;',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '0',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'component_text_tabs_tabs_repeater',
				'label' => 'Tabs',
				'name' => 'tabs_repeater',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 1,
				'max' => '',
				'layout' => 'block',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'component_text_tabs_tabs_repeater_title',
						'label' => 'Tab Title',
						'name' => 'tab_title',
						'type' => 'text',
						'instructions' => '&nbsp;',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'component_text_tabs_tabs_repeater_content',
						'label' => 'Tab Content',
						'name' => 'tab_content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => '',
						'toolbar' => 'basic',
						'media_upload' => 1,
						'delay' => 1,
					),
				),
			),
		),
	)
);
